"""silver_layer

Revision ID: 0003
Revises: 0002
Create Date: 2026-09-15 16:09:06.535643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0003'
down_revision: Union[str, Sequence[str], None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('name_normalized', sa.String(length=200), nullable=False),
    sa.Column('biz_no', sa.String(length=20), nullable=True),
    sa.Column('industry_code', sa.String(length=20), nullable=True),
    sa.Column('industry_name', sa.String(length=100), nullable=True),
    sa.Column('size_category', sa.String(length=20), nullable=True),
    sa.Column('homepage', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name_normalized', name='uq_companies_name_normalized')
    )
    op.create_index('uq_companies_biz_no', 'companies', ['biz_no'], unique=True, postgresql_where=sa.text('biz_no IS NOT NULL'))
    op.create_table('jobs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('source_id', sa.String(length=64), nullable=False),
    sa.Column('company_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sections', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('job_category', sa.String(length=50), nullable=True),
    sa.Column('employment_type', sa.String(length=20), nullable=True),
    sa.Column('exp_min', sa.SmallInteger(), nullable=True),
    sa.Column('exp_max', sa.SmallInteger(), nullable=True),
    sa.Column('education', sa.String(length=20), nullable=True),
    sa.Column('salary_min', sa.Integer(), nullable=True),
    sa.Column('salary_max', sa.Integer(), nullable=True),
    sa.Column('salary_raw', sa.String(length=200), nullable=True),
    sa.Column('region_code', sa.String(length=20), nullable=True),
    sa.Column('region_name', sa.String(length=100), nullable=True),
    sa.Column('posted_at', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), server_default=sa.text("'open'"), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('parse_flags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(description, ''))", persisted=True), nullable=True),
    sa.CheckConstraint("status IN ('open', 'closed', 'expired')", name='ck_jobs_status'),
    sa.CheckConstraint('exp_max IS NULL OR exp_min IS NULL OR exp_max >= exp_min', name='ck_jobs_exp_range'),
    sa.CheckConstraint('exp_min IS NULL OR exp_min >= 0', name='ck_jobs_exp_min_nonneg'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source', 'source_id', name='uq_jobs_source_id')
    )
    op.create_index('ix_jobs_company', 'jobs', ['company_id'], unique=False)
    op.create_index('ix_jobs_exp', 'jobs', ['exp_min', 'exp_max'], unique=False)
    op.create_index('ix_jobs_region_category', 'jobs', ['region_code', 'job_category'], unique=False)
    op.create_index('ix_jobs_search_tsv', 'jobs', ['search_tsv'], unique=False, postgresql_using='gin')
    op.create_index('ix_jobs_status_deadline', 'jobs', ['status', 'deadline'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_jobs_status_deadline', table_name='jobs')
    op.drop_index('ix_jobs_search_tsv', table_name='jobs', postgresql_using='gin')
    op.drop_index('ix_jobs_region_category', table_name='jobs')
    op.drop_index('ix_jobs_exp', table_name='jobs')
    op.drop_index('ix_jobs_company', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index('uq_companies_biz_no', table_name='companies', postgresql_where=sa.text('biz_no IS NOT NULL'))
    op.drop_table('companies')
    # ### end Alembic commands ###
