"""skills

Revision ID: 0004
Revises: 0003
Create Date: 2026-09-15 16:19:35.994934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('canonical_name', sa.String(length=80), nullable=False),
    sa.Column('aliases', postgresql.ARRAY(sa.String(length=80)), server_default=sa.text("'{}'"), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('match_patterns', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("category IN ('language', 'framework', 'database', 'cloud', 'tool', 'soft', 'domain')", name='ck_skills_category'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('canonical_name', name='uq_skills_canonical_name')
    )
    op.create_index('ix_skills_aliases', 'skills', ['aliases'], unique=False, postgresql_using='gin')
    op.create_table('job_skills',
    sa.Column('job_id', sa.BigInteger(), nullable=False),
    sa.Column('skill_id', sa.Integer(), nullable=False),
    sa.Column('is_required', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('occurrences', sa.SmallInteger(), server_default=sa.text('1'), nullable=False),
    sa.Column('confidence', sa.REAL(), server_default=sa.text('1.0'), nullable=False),
    sa.Column('extracted_by', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_job_skills_confidence'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('job_id', 'skill_id')
    )
    op.create_index('ix_job_skills_skill', 'job_skills', ['skill_id', 'is_required'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_job_skills_skill', table_name='job_skills')
    op.drop_table('job_skills')
    op.drop_index('ix_skills_aliases', table_name='skills', postgresql_using='gin')
    op.drop_table('skills')
    # ### end Alembic commands ###
